TradeUnion/Controllers/IntroUnionController.cs
using System.Web.Mvc;

namespace TradeUnion.Controllers
{
    public class IntroUnionController : Controller
    {
        #region --返回视图
        /// <summary>
        /// 工会职能
        /// </summary>
        /// <returns></returns>
        // GET: IntroUnion
        public ActionResult IntroUnionIndex()
        {
            return View();
        }
        #endregion
    }
}

TradeUnion/Controllers/JoinUsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TradeUnion.Controllers
{
    public class JoinUsController : Controller
    {
        #region --返回视图
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: JoinUs
        public ActionResult JoinUsIndex()
        {
            return View();
        }
        #endregion
    }
}

TradeUnion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>工会日常工作管理系统</title>
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/jquery-ui.css" rel="Stylesheet" />
    <link href="~/Content/css/mainfont.css" rel="Stylesheet" />
    <link href="~/Content/css/vertical menu.css" rel="Stylesheet" />
    <link href="~/Content/css/footer.css" rel="Stylesheet" />
    <link href="~/Content/css/tab carousel.css" rel="Stylesheet" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>


<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首页资讯", "HomeIndex", "Home")</li>
                    <li>@Html.ActionLink("工会职能", "UnionFunctionIndex", "UnionFunction")</li>
                    <li>@Html.ActionLink("工会信息", "UnionFunctionIndex", "UnionFunction")</li>
                    <li>@Html.ActionLink("工会成员", "UnionFunctionIndex", "UnionFunction")</li>
                    <li>@Html.ActionLink("教职工福利", "UnionFunctionIndex", "UnionFunction")</li>
                    <li>@Html.ActionLink("教职工家属", "UnionFunctionIndex", "UnionFunction")</li>
                </ul>             
        </div>
    </div>
</div>







@RenderBody()

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)

<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
</body>
</html>

TradeUnion/Views/Shared/_UnionLeft.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <link href="~/Content/css/bootstrap.css" rel="Stylesheet" />
    <link href="~/Content/css/jquery-ui.css" rel="Stylesheet" />
    <link href="~/Content/css/vertical menu.css" rel="Stylesheet" />
    <link href="~/Content/css/footer.css" rel="Stylesheet" />
    <link href="~/font-awesome-4.7.0/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/css/navileft.css" rel="stylesheet" />
    <link href="~/Content/css/RenderBody.css" rel="stylesheet" />

    <script src="~/Scripts/jquery.js" language="javascript" type="text/javascript"></script>
    <script src="~/Scripts/jquery-ui.js" language="javascript" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js" language="javascript" type="text/javascript"></script>
    <script src="~/Scripts/navileft.js" language="javascript" type="text/javascript"></script>
    <script src="~/Scripts/vertical menu.js" language="javascript" type="text/javascript"></script>
</head>

<style>
    li {
        height: 2.5em;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-3" style="height:500px;width:265px;">

                <ul class="nav nav-pills nav-stacked admin-menu ">
                    <li class="active"><nobr><a><i class="fa fa-home fa-2x fa-fw"></i>@Html.ActionLink("工会简介", "IntroUnionIndex", "IntroUnion")</a></nobr></li>



                    <li><nobr><a><i class="fa fa-tasks fa-2x fa-fw"></i>@Html.ActionLink("工会信息", "UnionInforIndex", "UnionInfor")</a></nobr></li>
                    
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-institution fa-fw"></i><a href="/UnionInfor/AddUnionArchiIndex">添加工会架构信息</a></a></nobr></li>

                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-balance-scale fa-fw"></i>@Html.ActionLink("发布工会政策法规", "AddUnionPolicyIndex", "UnionInfor")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-info fa-fw"></i>@Html.ActionLink("发布最新公告", "AddUnionAnnounIndex", "UnionInfor")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("查看架构信息", "ScanUnionArchiIndex", "UnionInfor")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("浏览工会政策法规", "ScanUnionPolicyIndex", "UnionInfor")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("查看最新公告", "ScanUnionAnnounIndex", "UnionInfor")</a></nobr></li>

                    <li><nobr><a><i class="fa fa-id-card fa-2x fa-fw"></i>@Html.ActionLink("工会成员管理", "UnionMembersIndex", "UnionMembers")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-address-card fa-fw"></i>@Html.ActionLink("新增工会成员", "AddUnionMembersIndex", "UnionMembers")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-cog fa-spin"></i>@Html.ActionLink("成员管理", "ScanUnionMembersIndex", "UnionMembers")</a></nobr></li>

                    <li><nobr><a><i class="fa fa-heart fa-2x fa-fw"></i>@Html.ActionLink("教职工福利", "EmployeeBenefitsIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-heartbeat fa-fw"></i>@Html.ActionLink("新增体检信息", "AddBodyExamIndex", "EmployeeBenefits")</a></nobr></li>
                    @*<li style="padding-left:35px;"><nobr><a><i class="fa fa-child fa-fw"></i>@Html.ActionLink("文体活动添加", "AddActivityIndex", "EmployeeBenefits")</a></nobr></li>*@
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-birthday-cake fa-fw"></i>@Html.ActionLink("添加教职工生日信息", "AddBirthdayIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-area-chart fa-fw"></i>@Html.ActionLink("新增健康基金保险", "AddInsuranceIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-user-o fa-fw"></i>@Html.ActionLink("添加特殊情况", "AddSpecialIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-medkit fa-fw"></i>@Html.ActionLink("查看体检信息", "ScanBodyExamIndex", "EmployeeBenefits")</a></nobr></li>
                    @*<li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("文体活动通知", "ScanActivityIndex", "EmployeeBenefits")</a></nobr></li>*@
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("校对教职工生日信息", "ScanBirthdayIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-pie-chart fa-fw"></i>@Html.ActionLink("浏览健康基金保险情况", "ScanInsuranceIndex", "EmployeeBenefits")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-user-o fa-fw"></i>@Html.ActionLink("管理特殊情况", "ScanSpecialIndex", "EmployeeBenefits")</a></nobr></li>

                    <li><nobr><a><i class="fa fa-user fa-2x fa-fw"></i>@Html.ActionLink("教职工家属", "EmployeeFamilyIndex", "EmployeeFamily")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-user-plus fa-fw"></i>@Html.ActionLink("新增子女信息", "AddChildIndex", "EmployeeFamily")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-user-o fa-fw"></i>@Html.ActionLink("增加特殊情况", "AddChildStatusIndex", "EmployeeFamily")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-eye fa-fw"></i>@Html.ActionLink("查看子女信息", "ScanChildIndex", "EmployeeFamily")</a></nobr></li>
                    <li style="padding-left:35px;"><nobr><a><i class="fa fa-user-o fa-fw"></i>@Html.ActionLink("管理特殊情况", "ScanChildStatusIndex", "EmployeeFamily")</a></nobr></li>

                    @*<li><nobr><a><i class="fa fa-paperclip fa-2x fa-fw"></i>@Html.ActionLink("加入我们", "JoinUsIndex", "JoinUs")</a></nobr></li>*@

                </ul>

        </div>
    </div>
</div>

<div class="RenderBody">
    @RenderBody()
</div>