TradeUnion/Models/Login.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

/// <summary>
/// TB_Admin 表实体类
/// </summary>
namespace Models
{
    public class Login
    {
        public int ID
        {
            get;
            set;
        }
        public string UserName
        {
            get;
            set;
        }
        public string PassWord
        {
            get;
            set;
        }
    }
}

TradeUnion/Controllers/LoginController.cs
using SQLServerDal;
using System.Data;
using System.Web.Mvc;
using TU.Model.Models;

namespace TradeUnion.Controllers
{

    public class LoginController : Controller
    {
        /// <summary>
        /// 返回该控制器的视图
        /// </summary>
        /// <returns></returns>
        // GET: Login
        public ActionResult LoginIndex()
        {
            return View();
        }

        //public Admin GetUserInforByName(string username)
        //{
        //    string s1 = "select * from TB_Admin where UserName = '{0}'";
        //    string sql = string.Format(s1, username);
        //    var dt = SQLHelper.GetDataSet(sql).Tables[0];
        //    var data = Query<Admin>(sql);
        //    return dt;
        //}

        /// <summary>
        /// 账号密码检查方法
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>

        [HttpPost]
        public ActionResult LoginAction(Login model)
        {
            string name = model.UserName;  //name 为 输入框中  name为UserName 值
            string pwd = model.PassWord; //pwd 为 视图中获取的 输入框中 name为PassWord 值

            SQLHelper sqlCheck = new SQLHelper(); //创建数据库工具类的对象
            string Adminsql = "select * from TB_Admin where UserName='{0}' and Password='{1}' "; //SQL查询语句
            string Admin = string.Format(Adminsql, name, pwd); //把SQL语句 和参数整合在一个字符串里
            DataTable dt = SQLHelper.GetDataSet(Admin).Tables[0]; //调用工厂类的方法进行查询并获取返回值
            if (dt.Rows.Count > 0) //如果获取到数据，行高>0 ; 如果没有获取到数据，行高=0；
            {
                Adminsql = "select * from TB_Admin where UserName='{0}' and Password='{1}' ";
                Admin = string.Format(Adminsql, name, pwd);
                //var usermodel = GetUserInforByName(Admin);
                ViewData.Model = model.UserName;
                Session["UserAccount"] = model.UserName;
                return RedirectToAction("UnionInforIndex", "UnionInfor"); //重定向到控制器Home 中的HomeIndex方法
            }
            else
            {
                return Redirect("LoginIndex");//重定向到本控制器中的LoginIndex方法
            }
        }
    }

}

TradeUnion/Controllers/SignUpController.cs
using System.Data.SqlClient;
using System.Web.Mvc;
using TU.Model.Models;

namespace TradeUnion.Controllers
{
    public class SignUpController : Controller
    {
        #region ---返回视图
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        // GET: SignUp
        public ActionResult SignUpIndex()
        {
            return View();
        }
        #endregion

        #region ---注册用户
        public ActionResult AddNewAccountAction(Admin model)
        {
            SQLHelper sqlh = new SQLHelper();
            const string AddEyeBeftsql = @"INSERT INTO dbo.TB_Admin
                                       ( UserName,PassWord)
                                        VALUES  ( @UserName, 
                                                  @PassWord
            ) ";
            SqlParameter[] para = new SqlParameter[]
            {
              new SqlParameter("UserName",model.UserName),
              new SqlParameter("PassWord", model.PassWord)
             };
            sqlh.ExecData(AddEyeBeftsql, para);
            return RedirectToAction("LoginIndex", "Login");
        }

        #endregion
    }
}

TradeUnion/Views/Login/LoginIndex.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/jquery-ui.css" rel="Stylesheet" />
    <link href="~/Content/css/mainfont.css" rel="Stylesheet" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <title>工会日常工作管理系统</title>
</head>
<body>
    
    
    
    
    

    <form action="/Login/LoginAction" method="post">
        <div class="container">
            <div class="jumbotron">
                <h2>登录您的工会日常工作管理系统</h2>
                <div class="row">
                    <div class="col-md-6">
                        <div>更有效的职工管理</div>
                        <ul class="list-unstyled" style="line-height: 2">
                            <li><span class="glyphicon glyphicon-ok"></span> 一切都井井有条</li>
                            <li><span class="glyphicon glyphicon-ok"></span> 更方便的人员管理</li>
                            <li><span class="glyphicon glyphicon-ok"></span> 员工福利发放</li>
                            <li><span class="glyphicon glyphicon-ok"></span> 事务信息快速通知</li>
                            <li><span class="glyphicon glyphicon-ok"></span> 更多惊喜等着您</li>
                            <li>@Html.ActionLink("还没有注册？快来创建一个！", "SignUpIndex", "SignUp")</li>
                        </ul>
                    </div>

                    <div class="col-md-6">
                        @* 教职工登录Tab *@
                        <div class="tab-pane active in" id="login">
                            <form>

                                <div class="form-group">
                                    <label>登录名</label>
                                    <input name="UserName" type="text" class="form-control" placeholder="输入您的登录名">
                                </div>


                                <div class="form-group">
                                    <label>密码</label>
                                    <input name="PassWord" type="password" class="form-control" placeholder="填写密码">
                                </div>

                                <button type="submit" class="btn btn-primary btn-sm">登录</button>
                                <button type="reset" class="btn btn-warning  btn-sm">重置</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </form>

    @*<div class="container">
        <div class="row">
            <div class="span12">
                <div class="" id="loginModal">

                    <div class="modal-header">                
                        <h3>Have an Account?</h3>
                    </div>

                    <div class="modal-body">
                        <div class="well">

                            <ul class="nav nav-tabs">
                                <li class="active"><a href="#login" data-toggle="tab">Login</a></li>
                                <li><a href="#create" data-toggle="tab">Create Account</a></li>
                            </ul>

                            <div id="myTabContent" class="tab-content">
                                <div class="tab-pane active in" id="login">
                                    <form class="form-horizontal" action='' method="POST">
                                        <fieldset>
                                            <div id="legend">
                                                <legend class="">Login</legend>
                                            </div>
                                            <div class="control-group">
                                                <!-- Username -->
                                                <label class="control-label" for="username">Username</label>
                                                <div class="controls">
                                                    <input type="text" id="username" name="username" placeholder="" class="input-xlarge">
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <!-- Password-->
                                                <label class="control-label" for="password">Password</label>
                                                <div class="controls">
                                                    <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
                                                </div>
                                            </div>


                                            <div class="control-group">
                                                <!-- Button -->
                                                <div class="controls">
                                                    <button class="btn btn-success">Login</button>
                                                </div>
                                            </div>
                                        </fieldset>
                                    </form>
                                </div>




                                <div class="tab-pane fade" id="create">
                                    <form id="tab">
                                        <label>Username</label>
                                        <input type="text" value="" class="input-xlarge">
                                        <label>First Name</label>
                                        <input type="text" value="" class="input-xlarge">
                                        <label>Last Name</label>
                                        <input type="text" value="" class="input-xlarge">
                                        <label>Email</label>
                                        <input type="text" value="" class="input-xlarge">
                                        <label>Address</label>
                                        <textarea value="Smith" rows="3" class="input-xlarge"></textarea>

                                        <div>
                                            <button class="btn btn-primary">Create Account</button>
                                        </div>
                                    </form>
                                </div>




                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>*@



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery-ui.js"></script>
</body>
</html>